import type { PermissionAction } from '../../modules/platform-administration/permissions/schemas/permission.schema.js';
import type { PermissionResource } from './permission-resources.js';

/**
 * Every (resourceType, action) pair the codebase actually guards, derived
 * from the `@RequirePermission` decorators themselves — not from the
 * 63 x 8 = 504 theoretical combinations, most of which correspond to no
 * route at all.
 *
 * This is the catalogue the bootstrap script seeds. Seeding the full cross
 * product instead would fill the dashboard's permission list with 340 rows
 * that gate nothing, which is the same "looks granted, guards nothing"
 * failure `PERMISSION_RESOURCES` was introduced to close, only larger.
 *
 * `permission-catalogue.spec.ts` re-derives this list from source on every
 * test run and fails if the two disagree in either direction, so adding a
 * new guarded route without updating this file is caught mechanically.
 */
export interface PermissionCatalogueEntry {
  resourceType: PermissionResource;
  action: PermissionAction;
}

export const PERMISSION_CATALOGUE: readonly PermissionCatalogueEntry[] = [
  { resourceType: 'aboutFederationPage', action: 'Create' },
  { resourceType: 'aboutFederationPage', action: 'Read' },
  { resourceType: 'aboutFederationPage', action: 'Delete' },
  { resourceType: 'ageCategories', action: 'Create' },
  { resourceType: 'ageCategories', action: 'Read' },
  { resourceType: 'ageCategories', action: 'Delete' },
  { resourceType: 'albums', action: 'Create' },
  { resourceType: 'albums', action: 'Read' },
  { resourceType: 'albums', action: 'Delete' },
  { resourceType: 'albums', action: 'Publish' },
  { resourceType: 'albumsPage', action: 'Update' },
  { resourceType: 'auditLogs', action: 'Read' },
  { resourceType: 'auditLogs', action: 'Export' },
  { resourceType: 'athleteClubHistory', action: 'Create' },
  { resourceType: 'athleteClubHistory', action: 'Read' },
  { resourceType: 'athleteClubHistory', action: 'Update' },
  { resourceType: 'athleteClubHistory', action: 'Delete' },
  { resourceType: 'athleteCoachHistory', action: 'Create' },
  { resourceType: 'athleteCoachHistory', action: 'Read' },
  { resourceType: 'athleteCoachHistory', action: 'Delete' },
  { resourceType: 'athleteGuardianRelationships', action: 'Create' },
  { resourceType: 'athleteGuardianRelationships', action: 'Read' },
  { resourceType: 'athleteGuardianRelationships', action: 'Delete' },
  { resourceType: 'athleteNationalTeamHistory', action: 'Create' },
  { resourceType: 'athleteNationalTeamHistory', action: 'Read' },
  { resourceType: 'athleteNationalTeamHistory', action: 'Delete' },
  { resourceType: 'athleteProfiles', action: 'Create' },
  { resourceType: 'athleteProfiles', action: 'Read' },
  { resourceType: 'athleteProfiles', action: 'Delete' },
  { resourceType: 'athletes', action: 'Create' },
  { resourceType: 'athletes', action: 'Read' },
  { resourceType: 'athletes', action: 'Delete' },
  { resourceType: 'athletes', action: 'Export' },
  { resourceType: 'athletesPage', action: 'Update' },
  { resourceType: 'boardMembersPage', action: 'Update' },
  { resourceType: 'clubs', action: 'Create' },
  { resourceType: 'clubs', action: 'Read' },
  { resourceType: 'clubs', action: 'Delete' },
  { resourceType: 'clubs', action: 'Export' },
  { resourceType: 'clubsPage', action: 'Update' },
  { resourceType: 'clubTeams', action: 'Create' },
  { resourceType: 'clubTeams', action: 'Read' },
  { resourceType: 'clubTeams', action: 'Delete' },
  { resourceType: 'coachClubHistory', action: 'Create' },
  { resourceType: 'coachClubHistory', action: 'Read' },
  { resourceType: 'coachClubHistory', action: 'Update' },
  { resourceType: 'coachClubHistory', action: 'Delete' },
  { resourceType: 'coaches', action: 'Create' },
  { resourceType: 'coaches', action: 'Read' },
  { resourceType: 'coaches', action: 'Delete' },
  { resourceType: 'coachesPage', action: 'Update' },
  { resourceType: 'committees', action: 'Create' },
  { resourceType: 'committees', action: 'Read' },
  { resourceType: 'committees', action: 'Delete' },
  { resourceType: 'committeesPage', action: 'Update' },
  { resourceType: 'contactMessages', action: 'Read' },
  { resourceType: 'contactMessages', action: 'Update' },
  { resourceType: 'contactMessages', action: 'Delete' },
  { resourceType: 'contactMessages', action: 'Export' },
  { resourceType: 'contactUsPage', action: 'Update' },
  { resourceType: 'countries', action: 'Create' },
  { resourceType: 'countries', action: 'Read' },
  { resourceType: 'countries', action: 'Delete' },
  { resourceType: 'disciplines', action: 'Create' },
  { resourceType: 'disciplines', action: 'Read' },
  { resourceType: 'disciplines', action: 'Delete' },
  { resourceType: 'disciplinesPage', action: 'Update' },
  { resourceType: 'documents', action: 'Create' },
  { resourceType: 'documents', action: 'Read' },
  { resourceType: 'documents', action: 'Delete' },
  { resourceType: 'electionCycles', action: 'Create' },
  { resourceType: 'electionCycles', action: 'Read' },
  { resourceType: 'electionCycles', action: 'Delete' },
  { resourceType: 'federation', action: 'Create' },
  { resourceType: 'federation', action: 'Read' },
  { resourceType: 'federation', action: 'Delete' },
  { resourceType: 'federationAppointments', action: 'Create' },
  { resourceType: 'federationAppointments', action: 'Read' },
  { resourceType: 'federationAppointments', action: 'Delete' },
  { resourceType: 'federationPersonnel', action: 'Create' },
  { resourceType: 'federationPersonnel', action: 'Read' },
  { resourceType: 'federationPersonnel', action: 'Delete' },
  { resourceType: 'governanceDocuments', action: 'Create' },
  { resourceType: 'governanceDocuments', action: 'Read' },
  { resourceType: 'governanceDocuments', action: 'Delete' },
  { resourceType: 'heroSlides', action: 'Create' },
  { resourceType: 'heroSlides', action: 'Read' },
  { resourceType: 'heroSlides', action: 'Delete' },
  { resourceType: 'mediaAssets', action: 'Create' },
  { resourceType: 'mediaAssets', action: 'Read' },
  { resourceType: 'mediaAssets', action: 'Delete' },
  { resourceType: 'navigationItems', action: 'Create' },
  { resourceType: 'navigationItems', action: 'Read' },
  { resourceType: 'navigationItems', action: 'Update' },
  { resourceType: 'navigationItems', action: 'Delete' },
  { resourceType: 'navigationMenus', action: 'Create' },
  { resourceType: 'navigationMenus', action: 'Read' },
  { resourceType: 'navigationMenus', action: 'Delete' },
  { resourceType: 'newsPage', action: 'Update' },
  { resourceType: 'notifications', action: 'Create' },
  { resourceType: 'officialAssignments', action: 'Create' },
  { resourceType: 'officialAssignments', action: 'Read' },
  { resourceType: 'officialAssignments', action: 'Delete' },
  { resourceType: 'officialClubHistory', action: 'Create' },
  { resourceType: 'officialClubHistory', action: 'Read' },
  { resourceType: 'officialClubHistory', action: 'Update' },
  { resourceType: 'officialClubHistory', action: 'Delete' },
  { resourceType: 'officialProfiles', action: 'Create' },
  { resourceType: 'officialProfiles', action: 'Read' },
  { resourceType: 'officialProfiles', action: 'Delete' },
  { resourceType: 'officials', action: 'Create' },
  { resourceType: 'officials', action: 'Read' },
  { resourceType: 'officials', action: 'Delete' },
  { resourceType: 'organizationalStructure', action: 'Create' },
  { resourceType: 'organizationalStructure', action: 'Read' },
  { resourceType: 'organizationalStructure', action: 'Update' },
  { resourceType: 'organizationalStructure', action: 'Delete' },
  { resourceType: 'pages', action: 'Create' },
  { resourceType: 'pages', action: 'Read' },
  { resourceType: 'pages', action: 'Delete' },
  { resourceType: 'pageSections', action: 'Create' },
  { resourceType: 'pageSections', action: 'Read' },
  { resourceType: 'pageSections', action: 'Delete' },
  { resourceType: 'permissions', action: 'Create' },
  { resourceType: 'permissions', action: 'Read' },
  { resourceType: 'presidentMessagePage', action: 'Create' },
  { resourceType: 'presidentMessagePage', action: 'Read' },
  { resourceType: 'presidentMessagePage', action: 'Delete' },
  { resourceType: 'publications', action: 'Read' },
  { resourceType: 'publications', action: 'Publish' },
  { resourceType: 'recordsPage', action: 'Update' },
  { resourceType: 'resultsRankingsPage', action: 'Update' },
  { resourceType: 'revisions', action: 'Create' },
  { resourceType: 'revisions', action: 'Read' },
  { resourceType: 'roles', action: 'Create' },
  { resourceType: 'roles', action: 'Read' },
  { resourceType: 'roles', action: 'Update' },
  { resourceType: 'roles', action: 'Delete' },
  { resourceType: 'siteSettings', action: 'Read' },
  { resourceType: 'siteSettings', action: 'Update' },
  { resourceType: 'strategicPlansPage', action: 'Create' },
  { resourceType: 'strategicPlansPage', action: 'Read' },
  { resourceType: 'strategicPlansPage', action: 'Delete' },
  { resourceType: 'users', action: 'Create' },
  { resourceType: 'users', action: 'Read' },
  { resourceType: 'users', action: 'Update' },
  { resourceType: 'users', action: 'Export' },
  { resourceType: 'venues', action: 'Create' },
  { resourceType: 'venues', action: 'Read' },
  { resourceType: 'venues', action: 'Delete' },
  { resourceType: 'videos', action: 'Create' },
  { resourceType: 'videos', action: 'Read' },
  { resourceType: 'videos', action: 'Delete' },
  { resourceType: 'videosPage', action: 'Update' },
  { resourceType: 'visionMissionPage', action: 'Create' },
  { resourceType: 'visionMissionPage', action: 'Read' },
  { resourceType: 'visionMissionPage', action: 'Delete' },
  { resourceType: 'workflowActionHistory', action: 'Read' },
  { resourceType: 'workflowDefinitions', action: 'Create' },
  { resourceType: 'workflowDefinitions', action: 'Read' },
  { resourceType: 'workflowDefinitions', action: 'Delete' },
  { resourceType: 'workflowInstances', action: 'Create' },
  { resourceType: 'workflowInstances', action: 'Read' },
  { resourceType: 'workflowInstances', action: 'Update' },
  { resourceType: 'workflowInstances', action: 'Approve' },
  { resourceType: 'workflowPolicies', action: 'Create' },
  { resourceType: 'workflowPolicies', action: 'Read' },
  { resourceType: 'workflowSteps', action: 'Create' },
  { resourceType: 'workflowSteps', action: 'Read' },
  { resourceType: 'workflowSteps', action: 'Delete' },
];
